import express from 'express';
import { requireAuth } from '../middleware/auth.js';
import { listPosts, createPost, getPost, updatePost, deletePost } from '../controllers/post.controller.js';
const router = express.Router();
router.get('/', listPosts);
router.get('/:id', getPost);
router.post('/', requireAuth, createPost);
router.patch('/:id', requireAuth, updatePost);
router.delete('/:id', requireAuth, deletePost);
export default router;